Fix ambiguous relations of nova-cloud-controller
nova-cloud-controller relations to mysql and rabbitmq-server were
ambiguous, which caused errors during deployment, such as:

jujuclient.exc.EnvError: <Env Error - Details:
 {   'error': 'ambiguous relation: "nova-cloud-controller mysql" could refer to '
             '"nova-cloud-controller:shared-db mysql:shared-db"; '
             '"nova-cloud-controller:shared-db-cell mysql:shared-db"',
    'request-id': 5,
    'response': {}}

Updating relations so that they explicitely point to
"nova-cloud-controller:shared-db" and "nova-cloud-controller:amqp" fixes
the deployment.